### ISSUE TITLE
Tooltip not loading on https

### ISSUE THREAD

**Issue by jbsaige** [rubensayshi/gw2spidy#161]
Tested on Firefox and Chrome.  The console in Firefox reads as follows:
> Blocked loading mixed active content "http://www.gw2spidy.com/api/v0.9/json/item-tooltip/11230&callback=WP_OnTooltipLoaded?_=1425411223331"

The offending code appears to be at /webroot/assets/js/tooltip.js:307
```javascript
var e = "http://" + window.location.host;
```

**Comment by rubensayshi** [comment]
is this on gw2spidy.com or is it on another site loading tooltips from gw2spidy somehow?

**Comment by rubensayshi** [comment]
fixed it
