### ISSUE TITLE
Find if item is unable to be sold

### ISSUE THREAD

**Issue by JamEngulfer** [rubensayshi/gw2spidy#165]
On the website, search results are automatically filtered so that items that can't be sold on the trading post don't show up. An item search on the API doesn't seem to support such functionality and there seems to be no way of getting an individual item's flag for whether it's sellable or not. 

Ideally, we would be able to add a flag to the item search url to filter out unsellable items. However, even just including the flag with the results would be great.

**Comment by keneanung** [comment]
Fixed since 1b6f4bf80e7d460c084a71585ddc787c030583c7. You should close it @rubensayshi :grinning:

**Comment by rubensayshi** [comment]
:rocket:
