### ISSUE TITLE
Filtering via API

### ISSUE THREAD

**Issue by Zyles** [rubensayshi/gw2spidy#167]
I want to do this query via API:

http://www.gw2spidy.com/type/18?rarity_filter=6&min_level=&max_level=&unsellable_flag=1

To get all the ascended weapon/armor etc. into an array.

Does not seem possible?

**Comment by rubensayshi** [comment]
http://www.gw2spidy.com/api/v0.9/json/items/18?rarity=6

**Comment by Zyles** [comment]
Than you, the issue was with the other error I couldn't get it to work.
