### ISSUE TITLE
Bug in crafting recipes

### ISSUE THREAD

**Issue by kirara** [rubensayshi/gw2spidy#174]
Opening https://www.gw2spidy.com/recipe/7005 result in...
Fatal error: Call to a member function getRarityLower() on a non-object in /var/sandbox/gw2spidy/src/GW2Spidy/GW2API/APIRecipe.php on line 74

**Comment by rubensayshi** [comment]
hmm I'm not getting that err but I'll look at the code to see if I can spot a reason why it would happen

**Comment by rubensayshi** [comment]
ah, it was a failing request to the anet gw2 api, I added a retry for it to avoid this problem
