### ISSUE TITLE
Navigate between recipe & item

### ISSUE THREAD

**Issue by PatrickKuijpers** [rubensayshi/gw2spidy#178]
Looks like I can navigate from an item to a recipe, but it is not possible (or I didn't yet find out how) to navigate the other way around.

Example navigation:
From: http://www.gw2spidy.com/item/46727
To: http://www.gw2spidy.com/recipe/7887
This is possible through the link below 'Created By'.

**Comment by PatrickKuijpers** [comment]
Just after I finished writing this feature, I finally found out how.
Closed issue!

**Comment by PastisD** [comment]
You can by cliking on the links under "Customize"
![fireshot screen capture 022 - hronk s magi insignia i gw2spidy - www_gw2spidy_com_recipe_7887](https://cloud.githubusercontent.com/assets/442023/11731279/7c8fe560-9f9a-11e5-9234-62543f70cfc8.jpg)
